version: '3.8'

services:
  app:
    build: .
    ports:
      - "8004:8004"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=camping
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRATION=86400000
    depends_on:
      - db
    networks:
      - camping-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=camping
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - camping-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  camping-network:
    driver: bridge 